### ISSUE TITLE
Python 3.11: asyncio coroutines deprecated & removed

### ISSUE THREAD

**Issue by Vrobenmat** [home-assistant-libs/aiowebostv#142]
Deprecated since version 3.8, will be removed in version 3.11: Passing coroutine objects to wait() directly is deprecated.

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/aiowebostv/webos_client.py", line 276, in connect_handler
    await asyncio.shield(closeout_task)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

**Comment by MartinHjelmare** [comment]
I think we're missing `asyncio.create_task` on this line:

https://github.com/home-assistant-libs/aiowebostv/blob/73e4c3f6904b29e64e51ed35ec7cc40278b5b194/aiowebostv/webos_client.py#L269

**Comment by sjuxax** [comment]
Confirmed changing that line to

`closeout.add(asyncio.create_task(callback(self)))`

gets rid of the error.

Arch just updated to Python 3.11 so this will probably become increasingly significant in coming weeks.

**Comment by thecode** [comment]
> Confirmed changing that line to
> 
> `closeout.add(asyncio.create_task(callback(self)))`
> 
> gets rid of the error.
> 
> Arch just updated to Python 3.11 so this will probably become increasingly significant in coming weeks.

Would you like to make a PR with this change?

**Comment by estebanz01** [comment]
hi! I took the liberty of creating the PR for this small change: https://github.com/home-assistant-libs/aiowebostv/pull/185

I also tried the possible suggestion made in here: https://github.com/home-assistant/core/issues/88990#issuecomment-1536694119 but that didn't throw the expected error when I denied the request for pairing, so Ieft that suggestion out.
