### ISSUE TITLE
I don't have a problem, just a little thank you

### ISSUE THREAD

**Issue by nexxai** [home-assistant-libs/aiowebostv#209]
Just wanted to thank you guys for this project. 

I use it as the interface for my TV and I built a small project around it (https://github.com/nexxai/LGTVMessenger)

I added a link to this repo in the Credits section of the README but if that's not enough, just let me know what I can do, and I'll do it.

Sending your team all the love! ❤️

**Comment by thecode** [comment]
Thanks @nexxai, you don't need to do anything. I appreciate linking to this repo 👍
